### ISSUE TITLE
Bit Manipulation concept codes

### ISSUE THREAD

**Issue by harshvardhan614** [saurav2127/hacktoberfest#10]
Hi @saurav2127 sir, Can I add a folder of Bit Manipulation CPP codes.
Please, accept my PR and merge it with the HActoberfest tag.

**Comment by Payalsahb20220** [comment]
Hello sir, i'm a beginner in github and want to contribute in your reposatory. As i know bit manipulation 
,so i'm little bit confidence that i remove your issue.
please accept my request.
